spring.application.name=ecom-application

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=admin
spring.datasource.password=admin

spring.h2.console.path=/h2-console
spring.h2.console.enabled=true

# Show SQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
#formatar e apresentar as linhas quebradas no console

spring.jpa.properties.hibernate.format_sql=true

#monitoramento actuator

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.shutdown.enabled=true

management.info.env.enabled=true
info.app.name=MyNewApp
info.app.description=App built by us
info.app.version=1.0.0


server.shutdown=graceful